# https://taskfile.dev
version: '3'

tasks:
  dev:
    desc: Start development of `backend` & `frontend`.
    aliases: [default]
    deps: [dev-frontend, dev-backend]

  dev:frontend: cd frontend && task
  dev:backend: cd backend && task
  build: bash ./build.sh
  preview: cd build/ && dotnet ./Api.dll

  restore:
    cmds:
      - cd frontend && task restore
      - cd backend && task restore
