# https://taskfile.dev
version: '3'

dotenv: ['.env']

tasks:
  dev:
    aliases: [default]
    desc: Start development of `backend` & `frontend`.
    deps: [fe:dev, be:dev]

  fe:dev: cd frontend && task
  be:dev: cd backend && task
  build: bash ./build.sh
  preview: cd build/ && dotnet ./Api.dll

  setup:
    cmds:
      - cd frontend && task setup
      - cd backend && task setup
