# https://taskfile.dev
version: '3'

dotenv: ['../.env']

tasks:
  default:
    cmds:
      - dotnet run --project ./src/Backend.Api/
    requires:
      vars: [PASSCODE]

  dev:
    cmds:
      - dotnet watch run --project ./src/Backend.Api/
    requires:
      vars: [PASSCODE]

  build: dotnet build --no-restore
  setup: dotnet restore ./Backend.slnx
